myshop.Web/Areas/Admin/Controllers/CatagoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using myshop.DataAccess.Data;
using myshop.Entities.Models;
using myshop.Entities.Repositories;
using myshop.Utilities;


namespace myshop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = SD.AdminRole)]
    public class CatagoryController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CatagoryController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            var catagory = _unitOfWork.Catagory.GetAll();
            return View(catagory);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(Catagory catagory)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Catagory.Add(catagory);
                _unitOfWork.Complete();
                TempData["Create"] = "Catagory Has been Created Successfully";
                return RedirectToAction("Index");
            }
            return View(catagory);

        }

        public IActionResult Update(int? Id)
        {
            if (Id == null || Id == 0)
                NotFound();
            var item = _unitOfWork.Catagory.GetFirstorDefault(x => x.Id == Id);
            return View(item);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Update(Catagory catagory)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.Catagory.Update(catagory);
                _unitOfWork.Complete();
                TempData["Update"] = "Catagory Has been Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(catagory);
        }
        public IActionResult Delete(int? Id)
        {
            if (Id == null || Id == 0)
                NotFound();
            var item = _unitOfWork.Catagory.GetFirstorDefault(x => x.Id == Id);
            return View(item);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult DeleteCatagory(int? Id)
        {
            var item = _unitOfWork.Catagory.GetFirstorDefault(x => x.Id == Id);
            if (item == null)
                NotFound();
            _unitOfWork.Catagory.Remove(item);
            _unitOfWork.Complete();
            TempData["Delete"] = "Catagory Has been Deleted Successfully";
            return RedirectToAction("Index");
        }

    }
}

myshop.Web/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using myshop.DataAccess.Data;
using myshop.Entities.Models;
using myshop.Entities.Repositories;
using myshop.Entities.ViewModels;
using myshop.Utilities;


namespace myshop.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles =SD.AdminRole)]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;

        }
        [HttpGet]
        public IActionResult GetData()
        {
            var products = _unitOfWork.Product.GetAll(IncludeWord: "TbCatagory");
            return Json(new { data = products });
        }

        public IActionResult Index()
        {
            var Product = _unitOfWork.Product.GetAll();
            return View(Product);
        }
        [HttpGet]
        public IActionResult Create()
        {
            ProductVM productVM = new ProductVM()
            {
                Product = new Product(),
                CatagoryList = _unitOfWork.Catagory.GetAll().Select(X => new SelectListItem
                {
                    Text = X.Name,
                    Value = X.Id.ToString()
                })
            };
            return View(productVM);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(ProductVM Productvm,IFormFile file)
        {
            if (ModelState.IsValid)
            {
                string rootPath = _webHostEnvironment.WebRootPath;
                if(file != null)
                {
                    string filename =Guid.NewGuid().ToString();
                    var Upload = Path.Combine(rootPath, @"dist\img\Products");
                    var extention = Path.GetExtension(file.FileName);
                    using (var fileStream = new FileStream(Path.Combine(Upload, filename + extention), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    Productvm.Product.Image = @"dist\img\Products\" + filename + extention;
                }
                _unitOfWork.Product.Add(Productvm.Product);
                _unitOfWork.Complete();
                TempData["Create"] = "Product Has been Created Successfully";
                return RedirectToAction("Index");
            }
            return View(Productvm.Product);

        }
        [HttpGet]
        public IActionResult Update(int? Id)
        {
            if (Id == null | Id == 0)
                NotFound();

            ProductVM productVM = new ProductVM()
            {
                Product = _unitOfWork.Product.GetFirstorDefault(x => x.Id == Id),
                CatagoryList = _unitOfWork.Catagory.GetAll().Select(X => new SelectListItem
                {
                    Text = X.Name,
                    Value = X.Id.ToString()
                })
            };
            return View(productVM);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Update(ProductVM Productvm, IFormFile? file)
        {
            if (ModelState.IsValid)
            {
                string rootPath = _webHostEnvironment.WebRootPath;
                if (file != null)
                {
                    string filename = Guid.NewGuid().ToString();
                    var Upload = Path.Combine(rootPath, @"dist\img\Products");
                    var extention = Path.GetExtension(file.FileName);
                    if (Productvm.Product.Image != null)
                    {
                        var oldimg = Path.Combine(rootPath, Productvm.Product.Image.TrimStart('\\'));
                        if (System.IO.File.Exists(oldimg))
                        {
                            System.IO.File.Delete(oldimg);
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(Upload, filename + extention), FileMode.Create))
                    {
                        file.CopyTo(fileStream);
                    }
                    Productvm.Product.Image = @"dist\img\Products\" + filename + extention;
                }
                _unitOfWork.Product.Update(Productvm.Product);
                _unitOfWork.Complete();
                TempData["Update"] = "Product Has been Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(Productvm.Product);
        }
        [HttpDelete]
        public IActionResult DeleteProduct(int? Id)
        {
            var item = _unitOfWork.Product.GetFirstorDefault(x => x.Id == Id);
            if (item == null)
                return Json(new { success = false, message = "Error While Deleting" });
            _unitOfWork.Product.Remove(item);
            var oldimg = Path.Combine(_webHostEnvironment.WebRootPath, item.Image.TrimStart('\\'));
            if (System.IO.File.Exists(oldimg))
            {
                System.IO.File.Delete(oldimg);
            }
            _unitOfWork.Complete();
            //TempData["Delete"] = "Product Has been Deleted Successfully"; // (Toaster)
            return  Json(new { success = true, message = "Product Has been Deleted Successfully" }); // (Sweetalert)
        }

    }
}

myshop.Web/Areas/Customer/Controllers/CartController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using myshop.Entities.Models;
using myshop.Entities.Repositories;
using myshop.Entities.ViewModels;
using myshop.Utilities;
using System.Security.Claims;

namespace myshop.Web.Areas.Customer.Controllers
{
	[Area("Customer")]
	[Authorize]
	public class CartController : Controller
	{
		private readonly IUnitOfWork _unitOfWork;
		public ShoppingCartVM shoppingCartVM { get; set; }
		public CartController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			shoppingCartVM = new ShoppingCartVM()
			{
				shoppingCarts = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == claim.Value,IncludeWord:"Product")
			};
			foreach(var item in shoppingCartVM.shoppingCarts)
			{
				shoppingCartVM.totalCarts += (item.Count * item.Product.Price);
			}
			return View(shoppingCartVM);
		}
		public IActionResult plus(int cartid) 
		{
			var shoppingCart = _unitOfWork.ShoppingCart.GetFirstorDefault(x => x.shoppingId == cartid);
			_unitOfWork.ShoppingCart.IncreaseCount(shoppingCart, 1);
			_unitOfWork.Complete();
			return RedirectToAction("Index");
		}
		public IActionResult Minus(int cartid) 
		{
			var shoppingCart = _unitOfWork.ShoppingCart.GetFirstorDefault(x => x.shoppingId == cartid);
			if (shoppingCart.Count <= 1)
			{
				_unitOfWork.ShoppingCart.Remove(shoppingCart);
				_unitOfWork.Complete();
				return RedirectToAction("Index", "Home");
			}
			_unitOfWork.ShoppingCart.decreaseCount(shoppingCart, 1);
			_unitOfWork.Complete();
			return RedirectToAction("Index");
		}
		public IActionResult Remove(int cartid)
		{
			var shoppingCart = _unitOfWork.ShoppingCart.GetFirstorDefault(x => x.shoppingId == cartid);
			_unitOfWork.ShoppingCart.Remove(shoppingCart);
			_unitOfWork.Complete();
			return RedirectToAction("Index");
		}
		[HttpGet]
		public IActionResult Summary()
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
			shoppingCartVM = new ShoppingCartVM()
			{
				shoppingCarts = _unitOfWork.ShoppingCart.GetAll(x => x.ApplicationUserId == claim.Value, IncludeWord: "Product"),
				OrderHeader = new()
			};
			shoppingCartVM.OrderHeader.applicationUser = _unitOfWork.ApplicationUser.GetFirstorDefault(X => X.Id == claim.Value);
			shoppingCartVM.OrderHeader.FirstName = shoppingCartVM.OrderHeader.applicationUser.FirstName;
			shoppingCartVM.OrderHeader.LastName = shoppingCartVM.OrderHeader.applicationUser.LastName;
			shoppingCartVM.OrderHeader.Email = shoppingCartVM.OrderHeader.applicationUser.Email;

            // Get Saved Past Transaction
            shoppingCartVM.OrderHeader.PhoneNumber = shoppingCartVM.OrderHeader.applicationUser.PhoneNumber;
            shoppingCartVM.OrderHeader.AdditionalPhoneNumber = shoppingCartVM.OrderHeader.applicationUser.AdditionalPhoneNumber;
            shoppingCartVM.OrderHeader.Address = shoppingCartVM.OrderHeader.applicationUser.Address;
            shoppingCartVM.OrderHeader.Region = shoppingCartVM.OrderHeader.applicationUser.Region;
            shoppingCartVM.OrderHeader.City = shoppingCartVM.OrderHeader.applicationUser.City;


            foreach (var item in shoppingCartVM.shoppingCarts)
			{
				shoppingCartVM.OrderHeader.totalPrice += (item.Count * item.Product.Price);
			}
			return View(shoppingCartVM);
		}
		[HttpPost]
		[ActionName("Summary")]
		[AutoValidateAntiforgeryToken]
		public IActionResult PostSummary(ShoppingCartVM shoppingCartvm)
		{
			var claimsIdentity = (ClaimsIdentity)User.Identity;
			var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            shoppingCartvm.shoppingCarts = _unitOfWork.ShoppingCart
				.GetAll(x => x.ApplicationUserId == claim.Value, IncludeWord: "Product");

            shoppingCartvm.OrderHeader.orderStatus = SD.Pending;
            shoppingCartvm.OrderHeader.paymentStatus = SD.Pending;
            shoppingCartvm.OrderHeader.orderDate = DateTime.Now;
            shoppingCartvm.OrderHeader.ApplicationUserId = claim.Value;

            var applicationUser = _unitOfWork.ApplicationUser.GetFirstorDefault(u => u.Id == claim.Value);
            // Update the user with the data from shoppingCartvm
            applicationUser.PhoneNumber = shoppingCartvm.OrderHeader.PhoneNumber;
            applicationUser.AdditionalPhoneNumber = shoppingCartvm.OrderHeader.AdditionalPhoneNumber;
            applicationUser.Address = shoppingCartvm.OrderHeader.Address;
            applicationUser.Region = shoppingCartvm.OrderHeader.Region;
            applicationUser.City = shoppingCartvm.OrderHeader.City;

            foreach (var item in shoppingCartvm.shoppingCarts)
			{
                shoppingCartvm.OrderHeader.totalPrice += (item.Count * item.Product.Price);
			}

			_unitOfWork.OrderHeader.Add(shoppingCartvm.OrderHeader);
			_unitOfWork.Complete();

			foreach(var item in shoppingCartvm.shoppingCarts)
			{
				OrderDetails orderDetails = new OrderDetails()
				{
					productId = item.ProductId,
                    OrderHeaderId = shoppingCartvm.OrderHeader.Id,
					price = item.Product.Price,
					Count =item.Count,
				};
				_unitOfWork.OrderDetails.Add(orderDetails);
				_unitOfWork.Complete();
			}
			return RedirectToAction("Index", "Home");
		}
	}
}

myshop.Web/Areas/Customer/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using myshop.Entities.Models;
using myshop.Entities.Repositories;
using System.Security.Claims;

namespace myshop.Web.Areas.Customer.Controllers
{
    [Area("Customer")]
	public class HomeController : Controller
	{
		private IUnitOfWork _unitOfWork;
        public HomeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
		{
			var products = _unitOfWork.Product.GetAll();
			return View(products);
		}
		public IActionResult Details(int id)
		{
			var product = _unitOfWork.Product.GetFirstorDefault(X => X.Id == id, IncludeWord: "TbCatagory");
            var relatedProducts = _unitOfWork.Product.GetAll(x => x.TbCatagory.Name == product.TbCatagory.Name && x.Id != id);
            ShoppingCart obj =new ShoppingCart()
			{
                ProductId =id,
                Product = product,
				Count = 1,
                RelatedProducts = relatedProducts
            };
			return View(obj);
		}
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public IActionResult Details(ShoppingCart shoppingCart)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            shoppingCart.ApplicationUserId = claim.Value;
            ShoppingCart cartObj = _unitOfWork.ShoppingCart.GetFirstorDefault(
                U => U.ApplicationUserId == claim.Value && U.ProductId == shoppingCart.ProductId
            );
            if (cartObj == null)
                _unitOfWork.ShoppingCart.Add(shoppingCart);
            else
            {
                _unitOfWork.ShoppingCart.IncreaseCount(cartObj,shoppingCart.Count);
            }
            _unitOfWork.Complete();
            return RedirectToAction("Index");
        }
    }
}

myshop.Web/Views/Shared/_Dashboard.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Alx Smart</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="~/Plugins/fontawesome-free/css/all.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="~/dist/css/adminlte.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
  <!--Data Table-->
  <link rel="stylesheet" href="//cdn.datatables.net/2.0.8/css/dataTables.dataTables.min.css">

   
</head>
<body class="hold-transition sidebar-mini">
<!-- Site wrapper -->
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="../../index3.html" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="#" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      <!-- Navbar Search -->
      <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
          <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
          <form class="form-inline">
            <div class="input-group input-group-sm">
              <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                  <i class="fas fa-search"></i>
                </button>
                <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                  <i class="fas fa-times"></i>
                </button>
              </div>
            </div>
          </form>
        </div>
      </li>

      <!-- Messages Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-comments"></i>
          <span class="badge badge-danger navbar-badge">3</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Brad Diesel
                  <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">Call me whenever you can...</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  John Pierce
                  <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">I got your message bro</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <!-- Message Start -->
            <div class="media">
              <img src="../../dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
              <div class="media-body">
                <h3 class="dropdown-item-title">
                  Nora Silvester
                  <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
                </h3>
                <p class="text-sm">The subject goes here</p>
                <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
              </div>
            </div>
            <!-- Message End -->
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
        </div>
      </li>
      <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-item dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="fullscreen" href="#" role="button">
          <i class="fas fa-expand-arrows-alt"></i>
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button">
          <i class="fas fa-th-large"></i>
        </a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="../../index3.html" class="brand-link">
      <img src="~/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">Perfume</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="~/dist/img/mo.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Mohamed Mosaad</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <li class="nav-item">
            <a href="#" class="nav-link">
              <i class="nav-icon fas fa-tachometer-alt"></i>
              <p>
                Dashboard
              </p>
            </a>
          </li>      
          <li class="nav-item">
            <a asp-controller="Product" class="nav-link">
                <i class="nav-icon fas fa-table"></i>
              <p>
                Product
              </p>
            </a>
          </li>      
          <li class="nav-item">
                  <a asp-controller="Catagory" class="nav-link">
                <i class="nav-icon fas fa-th"></i>
              <p>
                Catagory
              </p>
            </a>
          </li>       
          <li class="nav-item">
            <a href="#" class="nav-link">
               <i class="nav-icon fas fa-user"></i>
              <p>
                Users
              </p>
            </a>
          </li>       
          <li class="nav-item">
            <a href="#" class="nav-link">
                 <i class="far fa-circle nav-icon"></i>
              <p>
                Orders
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1>@ViewBag.pageTitle</h1>
          </div>
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Default box -->
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">@ViewBag.CardTitle</h3>

          <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" title="Collapse">
              <i class="fas fa-minus"></i>
            </button>
          </div>
        </div>
        <div class="card-body">
          <partial name="_Toaster" />
          @RenderBody()
        </div>
        <!-- /.card-body -->

        <!-- /.card-footer-->
      </div>
      <!-- /.card -->

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer">
    <strong>Copyright &copy; 2024 <a href="https://adminlte.io">SOFTEC</a>.</strong> All rights reserved.
  </footer>

  <!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="~/Plugins/jquery/jquery.min.js"></script>
<!-- Bootstrap 4 -->
<script src="~/Plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- AdminLTE App -->
<script src="~/dist/js/adminlte.min.js"></script>
<!--Data Table-->
<script src="//cdn.datatables.net/2.0.8/js/dataTables.min.js"></script>
<!--toater-->
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script> 
<!--SweetAlert-->
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

myshop.Web/Views/Shared/_Toaster.cshtml
@if (TempData["Create"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["success"]("@TempData["Create"]")
    </script>
}
@if (TempData["Update"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["info"]("@TempData["Update"]")
    </script>
}
@if (TempData["Delete"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr["error"]("@TempData["Delete"]")
    </script>
}